
package types;

public class AnalyticIneligibilityReason
{
    public enum Value
    {
		DISCOUNTTARGETREQUIRED,
		TEMPLATEDRATEUNAVAILABLE,
		PROJECTIONNOTALLOWED,
		PROJECTIONREQUIRED,
		TRADEDATEMISMATCH,
		LIBORBASISUNSUPPORTED,
		DISCOUNTROUTEMISSING,
		PROJECTIONROUTEMISSING,
		PAIRCURRENCYMISMATCH,
		COUPONPLANEMPTY,
		NOTIONALMODEUNSUPPORTED,
		RESETMAPPINGINVALID,
		CASHFLOWPLANUNSUPPORTED,
        N_VALUES
    }
}
