add_subdirectory(matrix_perf)
add_subdirectory(script_perf)
add_subdirectory(tape_perf)
add_subdirectory(jacobian_perf)
add_subdirectory(pde_perf)
add_subdirectory(rng_perf)
add_subdirectory(interp_perf)
add_subdirectory(krylov_perf)
add_subdirectory(banded_perf)
add_subdirectory(cholesky_perf)
add_subdirectory(specialfunctions_perf)
add_subdirectory(black_perf)
add_subdirectory(iv_brent_perf)
add_subdirectory(script_mc_perf)
add_subdirectory(curve_calibration_perf)
