function(optional_excel_check_private_headers)
    if(TARGET dal_excel_tests)
        set(test_target dal_excel_tests)
    elseif(TARGET dal_excel_portable_tests)
        set(test_target dal_excel_portable_tests)
    else()
        message(FATAL_ERROR "Private header probe requires an Excel test target")
    endif()
    get_target_property(public_includes DAL::public INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(public_links DAL::public INTERFACE_LINK_LIBRARIES)
    if(public_includes OR public_links)
        message(FATAL_ERROR "Private header probe requires a public target without includes or transitive dependencies")
    endif()
    set(public_includes "")
    set(public_links "")

    # Use the includes requested by the real test sources. Only the test target's
    # own include paths are supplied, so sibling public exports cannot mask gaps.
    get_target_property(test_sources "${test_target}" SOURCES)
    list(FILTER test_sources INCLUDE REGEX "/tests/")
    get_target_property(test_includes "${test_target}" INCLUDE_DIRECTORIES)
    set(headers)
    foreach(source IN LISTS test_sources)
        file(STRINGS "${source}" includes)
        list(FILTER includes INCLUDE REGEX "^#include[ \t]+<(dal-excel/|dal-public/tests/|tests/)")
        foreach(line IN LISTS includes)
            string(REGEX MATCH "<([^>]+)>" match "${line}")
            list(APPEND headers "${CMAKE_MATCH_1}")
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES headers)
    if(NOT headers)
        message(FATAL_ERROR "Private header probe found no Excel headers in the test sources")
    endif()
    set(core_fixtures "${headers}")
    list(FILTER core_fixtures INCLUDE REGEX "^tests/")
    if(NOT core_fixtures)
        message(FATAL_ERROR "Private header probe found no core fixtures in the test sources")
    endif()

    set(probe "")
    foreach(header IN LISTS headers)
        string(APPEND probe "#if !__has_include(<${header}>)\n#error Missing private header ${header}\n#endif\n")
    endforeach()
    # Compile the fixtures too, including their quoted relative and DAL includes.
    foreach(header IN LISTS core_fixtures)
        string(APPEND probe "#include <${header}>\n")
    endforeach()
    string(APPEND probe "int main() { return 0; }\n")
    file(WRITE "${CMAKE_BINARY_DIR}/private-headers-probe.cpp" "${probe}")
    include(CheckCXXSourceCompiles)
    set(CMAKE_REQUIRED_INCLUDES "${test_includes}")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    check_cxx_source_compiles("${probe}" OPTIONAL_EXCEL_PRIVATE_HEADERS_RESOLVABLE)
    file(WRITE "${CMAKE_BINARY_DIR}/private-headers.log"
        "target=${test_target}\nheaders=${headers}\ncore_fixtures=${core_fixtures}\n"
        "public_includes=${public_includes}\npublic_links=${public_links}\ntest_includes=${test_includes}\n"
        "resolvable=${OPTIONAL_EXCEL_PRIVATE_HEADERS_RESOLVABLE}\n")
    if(NOT OPTIONAL_EXCEL_PRIVATE_HEADERS_RESOLVABLE)
        message(FATAL_ERROR "${test_target} cannot compile its private headers and core fixtures")
    endif()
endfunction()
