function(optional_excel_check_private_headers)
    if(NOT TARGET dal_excel_tests)
        message(FATAL_ERROR "Private header probe requires dal_excel_tests")
    endif()
    get_target_property(public_includes DAL::public INTERFACE_INCLUDE_DIRECTORIES)
    if(public_includes)
        message(FATAL_ERROR "Private header probe requires a public target without include directories")
    endif()
    set(public_includes "")

    # Use the includes requested by the real test sources. Only the test target's
    # own include paths are supplied, so sibling public exports cannot mask gaps.
    get_target_property(test_sources dal_excel_tests SOURCES)
    get_target_property(test_includes dal_excel_tests INCLUDE_DIRECTORIES)
    set(headers)
    foreach(source IN LISTS test_sources)
        file(STRINGS "${source}" includes)
        list(FILTER includes INCLUDE REGEX "^#include[ \t]+<dal-excel/")
        foreach(line IN LISTS includes)
            string(REGEX MATCH "<(dal-excel/[^>]+)>" match "${line}")
            list(APPEND headers "${CMAKE_MATCH_1}")
        endforeach()
    endforeach()
    list(REMOVE_DUPLICATES headers)
    if(NOT headers)
        message(FATAL_ERROR "Private header probe found no Excel headers in the test sources")
    endif()

    set(probe "")
    foreach(header IN LISTS headers)
        string(APPEND probe "#if !__has_include(<${header}>)\n#error Missing private header ${header}\n#endif\n")
    endforeach()
    string(APPEND probe "int main() { return 0; }\n")
    include(CheckCXXSourceCompiles)
    set(CMAKE_REQUIRED_INCLUDES "${test_includes}")
    check_cxx_source_compiles("${probe}" OPTIONAL_EXCEL_PRIVATE_HEADERS_RESOLVABLE)
    file(WRITE "${CMAKE_BINARY_DIR}/private-headers.log"
        "headers=${headers}\npublic_includes=${public_includes}\ntest_includes=${test_includes}\n"
        "resolvable=${OPTIONAL_EXCEL_PRIVATE_HEADERS_RESOLVABLE}\n")
    if(NOT OPTIONAL_EXCEL_PRIVATE_HEADERS_RESOLVABLE)
        message(FATAL_ERROR "dal_excel_tests cannot resolve its private headers")
    endif()
endfunction()
