set(WIN32 FALSE)
if(DAL_OPTIONAL_EXCEL_PLATFORM STREQUAL "windows")
    set(WIN32 TRUE)
endif()

if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    return()
endif()

# Package visibility belongs to the case, not the host or a previous build.
set(CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH FALSE)
set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH FALSE)
set(CMAKE_FIND_USE_CMAKE_SYSTEM_PATH FALSE)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY FALSE)
set(CMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY FALSE)
set(CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/empty")
set(CMAKE_MODULE_PATH "${DAL_OPTIONAL_EXCEL_ROOT}/tests/optional-excel/packages")
set(dal-public_DIR "${CMAKE_BINARY_DIR}/empty" CACHE PATH "" FORCE)
if(DAL_OPTIONAL_EXCEL_PUBLIC STREQUAL "package")
    set(dal-public_DIR "${DAL_OPTIONAL_EXCEL_ROOT}/tests/optional-excel/packages" CACHE PATH "" FORCE)
endif()

include("${DAL_OPTIONAL_EXCEL_ROOT}/dal-public/cmake/DALBindingBoundary.cmake")
if(DAL_OPTIONAL_EXCEL_PUBLIC MATCHES "^(alias|both)$")
    add_library(DAL::public INTERFACE IMPORTED)
endif()
if(DAL_OPTIONAL_EXCEL_PUBLIC MATCHES "^(plain|both)$")
    add_library(dal_public INTERFACE IMPORTED)
endif()
if(DAL_OPTIONAL_EXCEL_GTEST STREQUAL "target")
    add_library(GTest::gtest_main INTERFACE IMPORTED)
endif()

function(optional_excel_record_targets)
    set(targets)
    foreach(target dal_excel DAL::excel dal_excel_tests dal_excel_portable_tests)
        if(TARGET "${target}")
            list(APPEND targets "${target}")
            if(NOT target STREQUAL "DAL::excel")
                get_target_property(links "${target}" LINK_LIBRARIES)
                file(APPEND "${CMAKE_BINARY_DIR}/excel-links.txt" "${target}=${links}\n")
            endif()
        endif()
    endforeach()
    file(WRITE "${CMAKE_BINARY_DIR}/excel-targets.txt" "${targets}")
endfunction()
cmake_language(DEFER CALL optional_excel_record_targets)
