cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED DAL_OPTIONAL_EXCEL_ROOT)
    get_filename_component(DAL_OPTIONAL_EXCEL_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
if(NOT DEFINED DAL_OPTIONAL_EXCEL_BINARY_DIR)
    set(DAL_OPTIONAL_EXCEL_BINARY_DIR "${DAL_OPTIONAL_EXCEL_ROOT}/build/optional-excel")
endif()

function(check_case name mode platform public excel portable tests gtest expected diagnostic)
    if(DEFINED DAL_OPTIONAL_EXCEL_CASE AND NOT name STREQUAL DAL_OPTIONAL_EXCEL_CASE)
        return()
    endif()
    set(case_dir "${DAL_OPTIONAL_EXCEL_BINARY_DIR}/${name}")
    file(REMOVE_RECURSE "${case_dir}")
    file(MAKE_DIRECTORY "${case_dir}/empty")
    set(source "${DAL_OPTIONAL_EXCEL_ROOT}")
    if(mode STREQUAL "standalone")
        set(source "${DAL_OPTIONAL_EXCEL_ROOT}/dal-excel")
    elseif(mode STREQUAL "sibling")
        set(source "${CMAKE_CURRENT_LIST_DIR}/sibling")
    endif()
    set(command "${CMAKE_COMMAND}" -S "${source}" -B "${case_dir}"
        "-DCMAKE_PROJECT_INCLUDE=${CMAKE_CURRENT_LIST_DIR}/project.cmake"
        "-DDAL_OPTIONAL_EXCEL_ROOT=${DAL_OPTIONAL_EXCEL_ROOT}"
        "-DDAL_OPTIONAL_EXCEL_PLATFORM=${platform}"
        "-DDAL_OPTIONAL_EXCEL_PUBLIC=${public}"
        "-DDAL_OPTIONAL_EXCEL_GTEST=${gtest}"
        "-DDAL_OPTIONAL_EXCEL_CHECK_PRIVATE_HEADERS=${ARGV10}"
        "-DDAL_BUILD_PUBLIC=${public}" "-DDAL_BUILD_EXCEL=${excel}"
        "-DDAL_BUILD_EXCEL_PORTABLE_TESTS=${portable}" "-DDAL_EXCEL_BUILD_TESTS=${tests}"
        -DDAL_CPP_BUILD_TESTS=OFF -DDAL_PUBLIC_BUILD_TESTS=OFF
        -DDAL_CPP_BUILD_EXAMPLES=OFF -DDAL_CPP_BUILD_BENCHMARKS=OFF
        -DDAL_BUILD_PYTHON=OFF -DDAL_USE_XAD_AAD=OFF
        -DDAL_USE_CODIPACK_AAD=OFF -DDAL_USE_ADEPT_AAD=OFF
        -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
        "--trace-source=${DAL_OPTIONAL_EXCEL_ROOT}/dal-excel/CMakeLists.txt"
        "--trace-source=${DAL_OPTIONAL_EXCEL_ROOT}/dal-public/cmake/DALBindingBoundary.cmake"
        --trace-expand "--trace-redirect=${case_dir}/trace.txt")
    if(DEFINED DAL_GENERATOR)
        list(APPEND command -G "${DAL_GENERATOR}")
    endif()
    if(DEFINED DAL_CXX_COMPILER)
        list(APPEND command "-DCMAKE_CXX_COMPILER=${DAL_CXX_COMPILER}")
    endif()
    if(DEFINED DAL_MAKE_PROGRAM)
        list(APPEND command "-DCMAKE_MAKE_PROGRAM=${DAL_MAKE_PROGRAM}")
    endif()
    execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    file(WRITE "${case_dir}/configure.log" "${output}\n${error}")
    file(READ "${case_dir}/trace.txt" trace)
    set(targets)
    foreach(target dal_excel DAL::excel dal_excel_tests dal_excel_portable_tests)
        if(trace MATCHES "add_(library|executable)\\(${target} ")
            list(APPEND targets "${target}")
        endif()
    endforeach()
    if(NOT "${targets}" STREQUAL "${expected}")
        message(FATAL_ERROR "${name}: Excel targets '${targets}', expected '${expected}': ${output}\n${error}")
    endif()
    if(diagnostic)
        if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "${diagnostic}")
            message(FATAL_ERROR "${name}: expected dependency failure '${diagnostic}', got ${result}: ${output}\n${error}")
        endif()
        if(diagnostic STREQUAL "Could NOT find GTest")
            if(NOT trace MATCHES "find_package\\(GTest REQUIRED *\\)")
                message(FATAL_ERROR "${name}: failure did not originate from the required GTest lookup")
            endif()
        elseif(mode STREQUAL "standalone")
            if(NOT trace MATCHES "find_package\\(dal-public CONFIG REQUIRED *\\)"
                OR NOT error MATCHES "dal-publicConfig.cmake")
                message(FATAL_ERROR "${name}: failure did not originate from the missing public package")
            endif()
        elseif(NOT trace MATCHES "message\\(FATAL_ERROR dal-excel requires DAL::public or dal_public target *\\)")
            message(FATAL_ERROR "${name}: failure did not originate from the missing sibling public target")
        endif()
    elseif(NOT result EQUAL 0)
        message(FATAL_ERROR "${name}: expected configuration success, got ${result}: ${output}\n${error}")
    else()
        file(READ "${case_dir}/excel-targets.txt" actual_targets)
        if(NOT "${actual_targets}" STREQUAL "${expected}")
            message(FATAL_ERROR "${name}: generated target set '${actual_targets}', expected '${expected}'")
        endif()
        foreach(target dal_excel dal_excel_portable_tests)
            if(target IN_LIST targets)
                file(READ "${case_dir}/excel-links.txt" links)
                set(public_target "DAL::public")
                if(public STREQUAL "plain")
                    set(public_target "dal_public")
                endif()
                if(NOT links MATCHES "${target}=${public_target}(;|\n)"
                    OR NOT trace MATCHES "get_target_property\\(direct_links ${target} LINK_LIBRARIES")
                    message(FATAL_ERROR "${name}: missing public link or real binding-boundary check: ${links}")
                endif()
            endif()
        endforeach()
    endif()
    if(expected STREQUAL "" AND NOT diagnostic)
        if(trace MATCHES "find_package\\(dal-public " OR trace MATCHES "set\\(DAL_PUBLIC_TARGET ")
            message(FATAL_ERROR "${name}: a no-target path resolved the public dependency")
        endif()
        if(platform STREQUAL "posix" AND (mode STREQUAL "standalone" OR excel OR portable))
            if(NOT output MATCHES "dal-excel: skipping XLL build")
                message(FATAL_ERROR "${name}: missing platform skip diagnostic")
            endif()
            if(tests AND NOT output MATCHES "GTest not found, skipping portable contract tests")
                message(FATAL_ERROR "${name}: missing GTest skip diagnostic")
            endif()
        endif()
    endif()
    if(NOT tests AND trace MATCHES "find_package\\(GTest ")
        message(FATAL_ERROR "${name}: tests OFF looked up GTest")
    endif()
    if(gtest STREQUAL "target" AND trace MATCHES "find_package\\(GTest ")
        message(FATAL_ERROR "${name}: an existing gtest_main target triggered package discovery")
    endif()
    message(STATUS "${name}: passed (configure=${result}, Excel targets='${targets}')")
endfunction()

check_case(core_tests_off workspace posix OFF OFF ON OFF poison "" "")
check_case(explicit_excel_tests_off workspace posix OFF ON OFF OFF poison "" "")
check_case(excel_not_entered workspace posix OFF OFF OFF ON poison "" "")
check_case(core_gtest_missing workspace posix OFF OFF ON ON missing "" "")
check_case(core_gtest_reported_without_target workspace posix OFF OFF ON ON reported "" "")
check_case(core_gtest_available workspace posix OFF OFF ON ON target "" "dal-excel requires DAL::public or dal_public target")
check_case(public_portable workspace posix ON OFF ON ON target "dal_excel_portable_tests" "")
check_case(public_explicit_excel workspace posix ON ON OFF ON package "dal_excel_portable_tests" "")
check_case(public_tests_off workspace posix ON OFF ON OFF poison "" "")
check_case(windows_excel_not_entered workspace windows OFF OFF ON ON poison "" "")
check_case(windows_public_missing workspace windows OFF ON ON OFF poison "" "dal-excel requires DAL::public or dal_public target")
check_case(windows_xll workspace windows ON ON OFF OFF poison "dal_excel;DAL::excel" "")
check_case(windows_xll_tests workspace windows ON ON OFF ON target "dal_excel;DAL::excel;dal_excel_tests" "")
check_case(windows_gtest_missing workspace windows ON ON OFF ON missing "dal_excel;DAL::excel" "Could NOT find GTest")

# Standalone package resolution and sibling target precedence are independent
# of the root options. These cases still configure the actual Excel project.
check_case(standalone_tests_off standalone posix OFF OFF ON OFF poison "" "")
check_case(standalone_gtest_missing standalone posix OFF OFF ON ON missing "" "")
check_case(standalone_public_missing standalone posix OFF OFF ON ON target "" "Could not find a package configuration file provided by")
check_case(standalone_portable standalone posix package OFF ON ON package "dal_excel_portable_tests" "")
check_case(standalone_windows_public_missing standalone windows OFF ON OFF OFF poison "" "Could not find a package configuration file provided by")
check_case(standalone_windows_xll standalone windows package ON OFF OFF poison "dal_excel;DAL::excel" "")
check_case(standalone_windows_tests standalone windows package ON OFF ON package "dal_excel;DAL::excel;dal_excel_tests" "")
check_case(standalone_windows_private_headers standalone windows package ON OFF ON package "dal_excel;DAL::excel;dal_excel_tests" "" ON)
check_case(standalone_windows_gtest_missing standalone windows package ON OFF ON missing "dal_excel;DAL::excel" "Could NOT find GTest")
check_case(sibling_alias sibling posix alias OFF ON ON target "dal_excel_portable_tests" "")
check_case(sibling_plain sibling posix plain OFF ON ON target "dal_excel_portable_tests" "")
check_case(sibling_both sibling posix both OFF ON ON target "dal_excel_portable_tests" "")
check_case(sibling_no_targets sibling posix OFF OFF ON OFF poison "" "")
check_case(sibling_windows_public_missing sibling windows OFF ON OFF OFF poison "" "dal-excel requires DAL::public or dal_public target")
check_case(sibling_windows_plain sibling windows plain ON OFF OFF poison "dal_excel;DAL::excel" "")
check_case(sibling_windows_both sibling windows both ON OFF ON target "dal_excel;DAL::excel;dal_excel_tests" "")
