# Inspect the real installed-package branch after the standalone project has
# declared its targets. This hook never supplies targets or runtime helpers.
function(optional_excel_audit_package directory prefix)
    file(REAL_PATH "${directory}" package_path)
    file(REAL_PATH "${prefix}" prefix_path)
    cmake_path(IS_PREFIX prefix_path "${package_path}" NORMALIZE inside_prefix)
    if(NOT inside_prefix)
        message(FATAL_ERROR "Package '${package_path}' is outside '${prefix_path}'")
    endif()
endfunction()

function(optional_excel_audit_installed)
    if(NOT CMAKE_HOST_WIN32 OR NOT MSVC OR NOT DAL_EXCEL_USES_INSTALLED_PUBLIC)
        message(FATAL_ERROR "Expected a real Windows/MSVC standalone installed-public build")
    endif()
    optional_excel_audit_package("${dal-public_DIR}" "${DAL_INSTALL_PREFIX}")
    optional_excel_audit_package("${dal-cpp_DIR}" "${DAL_INSTALL_PREFIX}")
    get_target_property(public_imported DAL::public IMPORTED)
    if(NOT public_imported OR NOT DAL_CPP_MSVC_RUNTIME_LIBRARY)
        message(FATAL_ERROR "Expected the installed public target and runtime contract")
    endif()

    set(expected_targets dal_excel DAL::excel)
    if(DAL_EXCEL_BUILD_TESTS)
        list(APPEND expected_targets dal_excel_tests)
        optional_excel_audit_package("${GTest_DIR}" "${DAL_GTEST_INSTALL_PREFIX}")
        get_target_property(gtest_library GTest::gtest_main IMPORTED_LOCATION_RELEASE)
        if(NOT EXISTS "${gtest_library}")
            message(FATAL_ERROR "Expected a real installed Release GTest library: ${gtest_library}")
        endif()
        optional_excel_audit_package("${gtest_library}" "${DAL_GTEST_INSTALL_PREFIX}")
    endif()
    set(actual_targets)
    foreach(target dal_excel DAL::excel dal_excel_tests dal_excel_portable_tests)
        if(TARGET "${target}")
            list(APPEND actual_targets "${target}")
        endif()
    endforeach()
    if(NOT "${actual_targets}" STREQUAL "${expected_targets}")
        message(FATAL_ERROR "Installed Excel targets '${actual_targets}', expected '${expected_targets}'")
    endif()

    file(WRITE "${CMAKE_BINARY_DIR}/runtime-contract.txt" "${DAL_CPP_MSVC_RUNTIME_LIBRARY}")
    file(WRITE "${CMAKE_BINARY_DIR}/installed-audit.log"
        "public=${dal-public_DIR}\ncore=${dal-cpp_DIR}\nconfig=${CMAKE_BUILD_TYPE}\ncontract=${DAL_CPP_MSVC_RUNTIME_LIBRARY}\n")
    foreach(target dal_excel dal_excel_tests)
        if(TARGET "${target}")
            get_target_property(runtime "${target}" MSVC_RUNTIME_LIBRARY)
            if(NOT "${runtime}" STREQUAL "${DAL_CPP_MSVC_RUNTIME_LIBRARY}")
                message(FATAL_ERROR "${target} runtime '${runtime}' differs from '${DAL_CPP_MSVC_RUNTIME_LIBRARY}'")
            endif()
            file(APPEND "${CMAKE_BINARY_DIR}/installed-audit.log" "${target}.runtime=${runtime}\n")
            message(STATUS "${target}: installed runtime contract matched: ${runtime}")
        endif()
    endforeach()
endfunction()

cmake_language(DEFER CALL optional_excel_audit_installed)
