// This file is auto-generated by machinist. Please don't modify it manually.
#pragma once

class UIRow_;
class Storable_;

struct  UnderdeterminedControls_ : StoreAsDictionary_<UnderdeterminedControls_>
{        
        int maxEvaluations_;
        int maxRestarts_;
        int maxBacktrackTries_;
        double restartTolerance_;
        double backtrackTolerance_;
        double maxBacktrack_;
        UnderdeterminedControls_(const Dictionary_& src);
        UnderdeterminedControls_(const Dictionary_& src, const std::map<String_, Handle_<Storable_>>&) : UnderdeterminedControls_(src) {}
        Dictionary_ Data() const;
};