cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED DAL_NATIVE_AAD_ROOT)
    get_filename_component(DAL_NATIVE_AAD_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()
if(NOT DEFINED DAL_NATIVE_AAD_BINARY_DIR)
    set(DAL_NATIVE_AAD_BINARY_DIR "${DAL_NATIVE_AAD_ROOT}/build/native-aad-configuration")
endif()

function(check_configuration name expected)
    if(DEFINED DAL_NATIVE_AAD_CASE AND NOT DAL_NATIVE_AAD_CASE STREQUAL name)
        return()
    endif()
    set(case_dir "${DAL_NATIVE_AAD_BINARY_DIR}/${name}")
    file(REMOVE_RECURSE "${case_dir}")
    set(command "${CMAKE_COMMAND}" -S "${DAL_NATIVE_AAD_ROOT}" -B "${case_dir}"
        -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF
        -DDAL_CPP_BUILD_TESTS=OFF -DDAL_CPP_BUILD_EXAMPLES=OFF
        -DDAL_CPP_BUILD_BENCHMARKS=OFF -DDAL_BUILD_PUBLIC=OFF
        -DDAL_BUILD_PYTHON=OFF -DDAL_BUILD_EXCEL=OFF
        -DDAL_BUILD_EXCEL_PORTABLE_TESTS=OFF ${ARGN})
    if(DEFINED DAL_GENERATOR)
        list(APPEND command -G "${DAL_GENERATOR}")
    endif()
    if(DEFINED DAL_CXX_COMPILER)
        list(APPEND command "-DCMAKE_CXX_COMPILER=${DAL_CXX_COMPILER}")
    endif()
    if(DEFINED DAL_MAKE_PROGRAM)
        list(APPEND command "-DCMAKE_MAKE_PROGRAM=${DAL_MAKE_PROGRAM}")
    endif()
    execute_process(COMMAND ${command} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
    file(MAKE_DIRECTORY "${case_dir}")
    file(WRITE "${case_dir}/configuration.log" "${output}\n${error}")
    if(expected STREQUAL "reject")
        if(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "no longer supported")
            message(FATAL_ERROR "${name}: expected explicit removed-backend rejection, got ${result}\n${output}\n${error}")
        endif()
    else()
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name}: native configuration failed (${result})\n${output}\n${error}")
        endif()
        file(READ "${case_dir}/dal-cpp/dal-cppConfig.cmake" config)
        if(NOT config MATCHES "set\\(DAL_CPP_AAD_BACKEND \"Native\"\\)")
            message(FATAL_ERROR "${name}: installed package configuration does not identify native AAD")
        endif()
    endif()
    message(STATUS "${name}: passed")
endfunction()

check_configuration(default accept)
check_configuration(legacy-off accept
    -DDAL_USE_XAD_AAD=OFF -DDAL_USE_CODIPACK_AAD=OFF -DDAL_USE_ADEPT_AAD=OFF)
check_configuration(diagnostics accept -DDAL_ENABLE_AAD_LIFETIME_DIAGNOSTICS=ON)
check_configuration(legacy-xad reject -DDAL_USE_XAD_AAD=ON)
check_configuration(legacy-codipack reject -DDAL_USE_CODIPACK_AAD=ON)
check_configuration(legacy-adept reject -DDAL_USE_ADEPT_AAD=ON)

function(check_header name macro)
    if(DEFINED DAL_NATIVE_AAD_CASE AND NOT DAL_NATIVE_AAD_CASE STREQUAL name)
        return()
    endif()
    set(case_dir "${DAL_NATIVE_AAD_BINARY_DIR}/${name}")
    file(REMOVE_RECURSE "${case_dir}")
    set(command "${CMAKE_COMMAND}" -S "${CMAKE_CURRENT_LIST_DIR}/header" -B "${case_dir}"
        "-DDAL_NATIVE_AAD_ROOT=${DAL_NATIVE_AAD_ROOT}")
    if(NOT macro STREQUAL "")
        list(APPEND command "-DDAL_REMOVED_AAD_MACRO=${macro}")
    endif()
    if(DEFINED DAL_GENERATOR)
        list(APPEND command -G "${DAL_GENERATOR}")
    endif()
    if(DEFINED DAL_CXX_COMPILER)
        list(APPEND command "-DCMAKE_CXX_COMPILER=${DAL_CXX_COMPILER}")
    endif()
    if(DEFINED DAL_MAKE_PROGRAM)
        list(APPEND command "-DCMAKE_MAKE_PROGRAM=${DAL_MAKE_PROGRAM}")
    endif()
    execute_process(COMMAND ${command} RESULT_VARIABLE result
        OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${name}: header fixture configuration failed\n${output}\n${error}")
    endif()
    execute_process(COMMAND "${CMAKE_COMMAND}" --build "${case_dir}" --config Release
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 120)
    file(WRITE "${case_dir}/compile.log" "${output}\n${error}")
    if(macro STREQUAL "")
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "${name}: native header compile failed\n${output}\n${error}")
        endif()
    elseif(result EQUAL 0 OR NOT "${output}\n${error}" MATCHES "no longer supported")
        message(FATAL_ERROR "${name}: expected removed macro rejection\n${output}\n${error}")
    endif()
    message(STATUS "${name}: passed")
endfunction()

check_header(native-header "")
check_header(legacy-xad-macro DAL_USE_XAD_AAD)
check_header(legacy-codipack-macro DAL_USE_CODIPACK_AAD)
check_header(legacy-adept-macro DAL_USE_ADEPT_AAD)
