# Generate dal.hpp header for the source_dir
function(generate_ql_header source_dir binary_dir)
    set(children_hpp "")
    set(children_dir "")
    file(WRITE "${binary_dir}/dal/dal.hpp"
            "/* This file is automatically generated; do not edit. */\n\n")
    file(GLOB children_hpp RELATIVE ${source_dir} "${source_dir}/dal/*.hpp")
    foreach(child ${children_hpp})
        file(APPEND "${binary_dir}/dal/dal.hpp" "#include <${child}>\n")
    endforeach()
    file(APPEND "${binary_dir}/ql/dal.hpp" "\n")
    file(GLOB children_dir RELATIVE ${source_dir} "${source_dir}/dal/*")
    list(FILTER children_dir EXCLUDE REGEX "CMakeFiles")
    list(FILTER children_dir EXCLUDE REGEX "^ql/\\..*")
endfunction()

# Entry point
generate_dal_header(${SOURCE_DIR} ${BINARY_DIR})