add_subdirectory(aad)
add_subdirectory(digital)
add_subdirectory(concurrency)
add_subdirectory(curve_calibration)
add_subdirectory(euribor3m_curve)
add_subdirectory(interpolate_curve)
add_subdirectory(joint_multi_curve_calibration)
add_subdirectory(xccy_curve_calibration)
add_subdirectory(european_mc)
add_subdirectory(european_fd)
add_subdirectory(snowball)
add_subdirectory(sobol)
add_subdirectory(script)
add_subdirectory(underdetermined)
add_subdirectory(uoc)
add_subdirectory(vanilla)
add_subdirectory(yield_curve_jacobian)

if(DAL_HAS_EXCEL)
    add_subdirectory(excelwriter)
endif()
